(() => {
  const TOKEN_KEY = "raisingGameToken";
  const state = { config:null, characters:[], query:"", filter:"", selected:null, user:null, theme:"light", onboardingStep:0, onboardingAnswers:[] };
  const app = document.querySelector("#app");
  const loginDialog = document.querySelector("#loginDialog");
  const unlockDialog = document.querySelector("#unlockDialog");
  const emailDialog = document.querySelector("#emailDialog");
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
  const getToken = () => { try { return localStorage.getItem(TOKEN_KEY) || ""; } catch { return ""; } };
  async function api(url, options = {}) {
    const headers = { "content-type":"application/json", ...(options.headers || {}) };
    const token = getToken(); if (token) headers.authorization = `Bearer ${token}`;
    const response = await fetch(url, { ...options, headers });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) { const error = new Error(payload.message || `Request failed (${response.status})`); Object.assign(error, payload, { status:response.status }); throw error; }
    return payload;
  }
  function imageFor(item) { return item.characterImageUrl || item.referenceImageUrl || item.posterUrl || item.localImageUrl || item.imageUrl || "/assets/brand/logo-mark.svg"; }
  function filteredCharacters() { const query = state.query.toLowerCase(); return state.characters.filter((item) => (!query || `${item.name} ${item.title} ${(item.tags || []).join(" ")}`.toLowerCase().includes(query)) && (!state.filter || String(item.gender || "").toLowerCase() === state.filter)); }
  function renderModels() {
    const items = filteredCharacters();
    app.innerHTML = `<section class="models-page"><div class="models-intro"><span class="eyebrow">DISCOVER</span><h1>Our Models</h1><p>Browse through our verified creators and find your perfect match.</p></div><div class="filter-bar"><input data-search placeholder="Search models..." value="${esc(state.query)}" /><select data-filter><option value="">All Locations</option><option value="female" ${state.filter === "female" ? "selected" : ""}>Female</option><option value="male" ${state.filter === "male" ? "selected" : ""}>Male</option></select><button class="search-button" data-search-button aria-label="Search">⌕</button></div><div class="model-grid">${items.length ? items.map(modelCard).join("") : `<div class="empty-state">No models match your search.</div>`}</div></section>`;
    app.querySelector("[data-search]")?.addEventListener("input", (event) => { state.query = event.target.value; renderModels(); });
    app.querySelector("[data-filter]")?.addEventListener("change", (event) => { state.filter = event.target.value; renderModels(); });
    app.querySelectorAll("[data-model-id]").forEach((card) => card.addEventListener("click", () => openDetail(card.dataset.modelId)));
  }
  function onboardingSteps() {
    const images = state.characters.slice(0, 12).map((item) => ({ image:imageFor(item), name:item.name || "Creator" }));
    return [
      { label:"Welcome", title:"Let’s find your perfect match", copy:"A few quick choices help us curate your private chat experience.", kind:"binary", options:["I’m 18 or older", "I’m under 18"] },
      { label:"Intent", title:"What are you looking for?", copy:"Choose the kind of connection you want to explore.", kind:"binary", options:["A private conversation", "Just browsing"] },
      { label:"Vibe", title:"Pick a vibe", copy:"Tell us what feels right today.", kind:"binary", options:["Playful and flirty", "Warm and romantic"] },
      { label:"Style", title:"Choose a style", copy:"Select a creator that catches your eye.", kind:"images", options:images.slice(0,4) },
      { label:"Energy", title:"What energy do you like?", copy:"You can change this later.", kind:"images", options:images.slice(4,8) },
      { label:"Mood", title:"Set the mood", copy:"One last preference before we show your matches.", kind:"images", options:images.slice(8,12) },
      { label:"Ready", title:"Your private space is ready", copy:"We’ve curated a selection of verified creators for you.", kind:"loading" }
    ];
  }
  function showOnboarding() {
    if (localStorage.getItem("vipsChatOnboardingDone") === "1") return false;
    const overlay = document.createElement("div"); overlay.className = "standalone-onboarding"; overlay.innerHTML = `<div class="onboarding-panel"><aside class="onboarding-rail"><div class="onboarding-brand">VIPS<span>CHAT</span></div><div data-onboarding-rail></div></aside><section class="onboarding-main"><div class="onboarding-head"><span>PRIVATE MATCHING</span><b data-onboarding-count></b></div><div class="onboarding-content"><div class="onboarding-icon">✦</div><h1 data-onboarding-title></h1><p data-onboarding-copy></p><div data-onboarding-body></div></div><button class="onboarding-skip" data-onboarding-skip type="button">Skip and browse models</button></section></div>`; document.body.appendChild(overlay);
    const steps = onboardingSteps();
    const rail = overlay.querySelector("[data-onboarding-rail]"), count = overlay.querySelector("[data-onboarding-count]"), title = overlay.querySelector("[data-onboarding-title]"), copy = overlay.querySelector("[data-onboarding-copy]"), body = overlay.querySelector("[data-onboarding-body]");
    const finish = () => { localStorage.setItem("vipsChatOnboardingDone", "1"); overlay.remove(); location.hash = "models"; route(); };
    const render = (step) => { state.onboardingStep = step; const current = steps[step]; count.textContent = `${Math.min(step + 1, steps.length)} / ${steps.length}`; rail.innerHTML = steps.map((item, index) => `<div class="onboarding-rail-item ${index === step ? "is-active" : ""} ${state.onboardingAnswers[index] ? "is-done" : ""}"><i>${index + 1}</i><span>${esc(item.label)}</span></div>`).join(""); title.textContent = current.title; copy.textContent = current.copy;
      if (current.kind === "loading") { body.innerHTML = `<div class="onboarding-loading"><span></span><div class="onboarding-progress"><i></i></div><small>Curating your matches...</small></div>`; setTimeout(() => render(step + 1), 1500); return; }
      if (current.kind === "images") body.innerHTML = `<div class="onboarding-images">${current.options.map((item, index) => `<button type="button" data-onboarding-option="${index}"><img src="${esc(item.image)}" alt="" /><span>${esc(item.name)}</span></button>`).join("")}</div>`;
      else body.innerHTML = `<div class="onboarding-choices">${current.options.map((item, index) => `<button type="button" class="${index ? "is-secondary" : ""}" data-onboarding-option="${index}">${esc(item)}<b>→</b></button>`).join("")}</div>`;
      body.querySelectorAll("[data-onboarding-option]").forEach((button) => button.addEventListener("click", () => { state.onboardingAnswers[step] = button.dataset.onboardingOption; if (step === 0 && button.dataset.onboardingOption === "1") { copy.textContent = "You must be 18 or older to continue."; return; } render(step + 1); }));
    };
    overlay.querySelector("[data-onboarding-skip]").addEventListener("click", finish); render(0); return true;
  }
  function modelCard(item) { return `<article class="model-card" data-model-id="${esc(item.id)}"><span class="country-badge">🌐</span><span class="free-badge">Free Chat</span><img src="${esc(imageFor(item))}" alt="${esc(item.name || "Model")}" loading="lazy" /><div class="model-card-body"><h3>${esc(item.name || "Model")}</h3><p>${esc((item.tags || []).slice(0,2).join(" · ") || item.style || "Verified creator")}</p></div></article>`; }
  function openDetail(id) { const item = state.characters.find((entry) => String(entry.id) === String(id)); if (!item) return; state.selected = item; location.hash = `model/${encodeURIComponent(item.id)}`; renderDetail(item); }
  function renderDetail(item) {
    const image = imageFor(item); const tags = (item.tags || []).slice(0,3); const media = (item.homeSceneVideos ? Object.values(item.homeSceneVideos) : []).filter((entry) => entry.posterUrl || entry.cdnPosterUrl).slice(0,2);
    app.innerHTML = `<section class="detail-page"><div class="detail-shell"><a class="back-link" href="#models">← Back to models</a><div class="profile-card"><img class="profile-avatar" src="${esc(image)}" alt="${esc(item.name)}" /><div class="profile-copy"><h1>${esc(item.name || "Model")} <span class="verified">✓</span></h1><div class="tag-row">${tags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div><div class="profile-actions"><button class="solid-button" data-detail-chat>◌ Chat</button><button class="outline-button" data-detail-love>♡ Love</button></div></div><div class="profile-features"><div class="feature-card"><span class="feature-icon">✓</span><strong>Private chat</strong><small>Personal replies</small></div><div class="feature-card"><span class="feature-icon" style="color:#5d9cff;background:#edf4ff">☏</span><strong>Free preview</strong><small>Message first</small></div><div class="feature-card"><span class="feature-icon" style="color:#a45cff;background:#f5edff">▣</span><strong>Paid content</strong><small>Exclusive media</small></div></div></div><div class="content-grid"><div class="media-card">${media.length ? media.map((entry) => `<div class="media-item"><img src="${esc(entry.posterUrl || entry.cdnPosterUrl || image)}" alt="Preview" /><strong>${esc(entry.sceneName || "Exclusive preview")}</strong><b>$45,00</b></div>`).join("") : `<div class="media-item"><img src="${esc(image)}" alt="Preview" /><strong>Private preview</strong><b>$45,00</b></div>`}</div><div class="unlock-box"><div class="unlock-lock">♙</div><h2>Unlock Exclusive Content</h2><p>Subscribe to access private chats, exclusive media, and special content from this creator.</p><div class="plans"><button class="plan is-selected" data-plan="tool-usd-10"><small>1 Month</small><strong>$9.99<small>/mo</small></strong></button><button class="plan" data-plan="tool-usd-20"><small>3 Months</small><strong>$8.99<small>/mo</small></strong><em>-10%</em></button><button class="plan" data-plan="tool-usd-50"><small>6 Months</small><strong>$7.99<small>/mo</small></strong><em>-20%</em></button><button class="plan" data-plan="tool-usd-50"><small>12 Months</small><strong>$6.99<small>/mo</small></strong><em>-30%</em></button></div><button class="solid-button subscribe-button" data-subscribe>Subscribe Now</button></div></div></div></section>`;
    app.querySelector("[data-detail-chat]")?.addEventListener("click", startChat); app.querySelector("[data-subscribe]")?.addEventListener("click", openUnlock); app.querySelectorAll("[data-plan]").forEach((button) => button.addEventListener("click", () => { app.querySelectorAll("[data-plan]").forEach((entry) => entry.classList.remove("is-selected")); button.classList.add("is-selected"); }));
  }
  async function startChat() { if (!state.selected) return; if (!getToken()) { loginDialog.showModal(); return; } try { const result = await api("/api/chat/conversations", { method:"POST", body:JSON.stringify({ characterId:state.selected.id }) }); location.hash = `chat/${encodeURIComponent(result.conversation.id)}`; window.alert("Chat unlocked. Your conversation is ready."); } catch (error) { if (error.status === 402 || error.code === "CHAT_UNLOCK_REQUIRED") openUnlock(); else window.alert(error.message); } }
  function openUnlock() { if (!getToken()) { loginDialog.showModal(); return; } unlockDialog.showModal(); renderUnlockOptions(); }
  function renderUnlockOptions() { const root = unlockDialog.querySelector("[data-unlock-options]"); root.innerHTML = [10,20,50].map((amount, index) => `<button class="plan ${index === 0 ? "is-selected" : ""}" type="button" data-unlock-package="tool-usd-${amount}"><small>${index === 0 ? "Starter" : index === 1 ? "Creator" : "Studio"}</small><strong>$${amount}</strong><span>${amount * 100} credits</span></button>`).join(""); root.querySelectorAll("[data-unlock-package]").forEach((button) => button.addEventListener("click", () => beginStripe(button.dataset.unlockPackage))); }
  async function beginStripe(packageId) { const message = unlockDialog.querySelector("[data-unlock-message]"); message.textContent = "Opening secure checkout..."; try { const result = await api("/api/pay/stripe/checkout-sessions", { method:"POST", body:JSON.stringify({ packageId, returnUrl:`${location.origin}${location.pathname}#model/${encodeURIComponent(state.selected?.id || "")}`, cancelUrl:location.href }) }); if (result.checkoutUrl) location.href = result.checkoutUrl; else message.textContent = "Checkout page is unavailable."; } catch (error) { message.textContent = error.message; } }
  async function load() { try { const result = await api("/api/config/public"); state.config = result.config; state.characters = result.config?.homeVideo?.items || []; const token = getToken(); if (token) { try { const me = await api("/api/auth/me"); state.user = me.user; document.querySelector("[data-account-label]").textContent = me.user?.username || me.user?.email || "My Account"; } catch {} } if (!showOnboarding()) route(); } catch (error) { app.innerHTML = `<div class="empty-state">Unable to load models: ${esc(error.message)}</div>`; } }
  function route() { const match = location.hash.match(/^#model\/(.+)$/); if (match) { const id = decodeURIComponent(match[1]); const item = state.characters.find((entry) => String(entry.id) === id); if (item) return renderDetail(item); } renderModels(); }
  document.addEventListener("click", (event) => { const action = event.target.closest("[data-action]")?.dataset.action; if (action === "models") { location.hash = "models"; route(); } if (action === "categories") { document.querySelector("[data-search]")?.focus(); } if (action === "account") { if (getToken()) { localStorage.removeItem(TOKEN_KEY); location.reload(); } else loginDialog.showModal(); } if (action === "theme") { document.body.classList.toggle("dark"); } if (action === "email-login") { loginDialog.close(); emailDialog.showModal(); } if (action === "request-email") requestEmailCode(); });
  document.querySelector("[data-login-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const message = form.querySelector("[data-login-message]"); try { const result = await api("/api/auth/login-or-register", { method:"POST", body:JSON.stringify({ username:form.username.value.trim(), password:form.password.value }) }); localStorage.setItem(TOKEN_KEY, result.token); loginDialog.close(); location.reload(); } catch (error) { message.textContent = error.message; } });
  async function requestEmailCode() { const form = document.querySelector("[data-email-form]"); const message = form.querySelector("[data-email-message]"); try { await api("/api/auth/email/request", { method:"POST", body:JSON.stringify({ email:form.email.value.trim() }) }); message.textContent = "Verification code sent."; } catch (error) { message.textContent = error.message; } }
  document.querySelector("[data-email-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const message = form.querySelector("[data-email-message]"); try { const result = await api("/api/auth/email/verify", { method:"POST", body:JSON.stringify({ email:form.email.value.trim(), code:form.code.value.trim() }) }); localStorage.setItem(TOKEN_KEY, result.token); emailDialog.close(); location.reload(); } catch (error) { message.textContent = error.message; } });
  window.addEventListener("hashchange", route); load();
})();
