(() => {
  const TOKEN_KEY = "raisingGameToken";
  const app = document.querySelector("#liveApp");
  const loginDialog = document.querySelector("#loginDialog");
  const state = { chars: [], rooms: [], config: null, user: null, conversations: [], billing: null, page: "home", category: "", role: null, language: localStorage.getItem("vipeakLanguage") || "zh", filters: { age: "", gender: "", style: "" } };
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const token = () => { try { return localStorage.getItem(TOKEN_KEY) || ""; } catch { return ""; } };
  async function api(url, options = {}) { const h = { "content-type": "application/json", ...(options.headers || {}) }; if (token()) h.authorization = `Bearer ${token()}`; const r = await fetch(url, { cache: "no-store", ...options, headers: h }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.message || `请求失败（${r.status}）`); return p; }
  const photo = (x) => x?.profilePhotos?.[0] || "";
  const rolePhoto = (x) => x?.portraitUrl || x?.avatarUrl || "";
  const label = (key) => ({ zh: { home: "首页", messages: "消息", profile: "我的", language: "语言", recommended: "为你推荐", online: "位在线", call: "拨打视频", vip: "订阅 VIP", edit: "编辑资料", save: "保存", cancel: "取消" }, en: { home: "Home", messages: "Messages", profile: "Me", language: "Language", recommended: "Recommended", online: "online", call: "Video call", vip: "VIP", edit: "Edit profile", save: "Save", cancel: "Cancel" }, ja: { home: "ホーム", messages: "メッセージ", profile: "マイページ", language: "言語", recommended: "おすすめ", online: "オンライン", call: "ビデオ通話", vip: "VIP", edit: "プロフィール編集", save: "保存", cancel: "キャンセル" } }[state.language] || {} )[key] || key;
  const nav = (active) => `<nav class="bottom-nav"><button class="${active === "home" ? "active" : ""}" data-nav="home"><span>⌂</span><small>${label("home")}</small></button><button class="${active === "messages" ? "active" : ""}" data-nav="messages"><span>◌</span><small>${label("messages")}</small></button><button class="${active === "profile" ? "active" : ""}" data-nav="profile"><span>♙</span><small>${label("profile")}</small></button></nav>`;
  const top = () => `<header class="live-top"><div class="live-brand"><span class="brand-icon">✣</span><div><div class="brand-title">Vipeak</div><div class="brand-sub">遇见你的专属伴侣</div></div></div><button class="language-globe" data-action="language-sheet" aria-label="${label("language")}">◎</button></header>`;
  const media = (url, alt = "") => url ? `<img src="${esc(url)}" alt="${esc(alt)}" loading="lazy">` : `<div class="image-empty"><span>♙</span></div>`;
  function roomCard(room) { const c = room.character || {}; return `<article class="room-card" data-room-id="${esc(room.id)}" data-room-character-id="${esc(room.characterId)}"><div class="room-image">${media(rolePhoto(c), c.name || "角色")}<span class="room-online">${Number(room.viewerCount || 0)} 人在房</span><span class="room-mode"><i></i>${esc(room.modeLabel || (room.mode === "voice" ? "语音房" : "视频房"))}</span></div><div class="room-copy"><strong>${esc(room.title || `${c.name || "角色"}的陪伴房`)}</strong><small>${Number(room.priceCreditsPerMinute || 0)} 积分/分钟 · ${esc(room.description || "一起聊聊")}</small></div></article>`; }
  function card(c) {
    const tags = (c.tags || []).slice(0, 3);
    const age = Number(c.age || 0) ? ` · ${Number(c.age)}岁` : "";
    return `<article class="person-card" data-role-id="${esc(c.id)}"><div class="person-image role-open">${media(rolePhoto(c), `${c.name || "角色"}的照片`)}<span class="status-pill"><i></i>在线</span><div class="person-copy"><span class="person-name">${esc(c.name || "角色")}</span><span class="person-meta">${esc(age)}</span><div class="person-intro">${esc(c.intro || c.greeting || "")}</div><div class="tag-row">${tags.map((x) => `<span class="tag">${esc(x)}</span>`).join("")}</div></div></div><div class="person-actions"><button class="video-button" data-call-id="${esc(c.id)}">▣ ${label("call")}</button></div></article>`;
  }
  function filterText() { return state.language === "en" ? "Filter" : state.language === "ja" ? "絞り込み" : "筛选"; }
  function filterSheet() {
    const groups = [
      ["age", "年龄", [["", "不限"], ["18-23", "18-23 岁"], ["24-26", "24-26 岁"], ["27-30", "27-30 岁"]]],
      ["gender", "性别", [["", "不限"], ["female", "女生"], ["male", "男生"]]],
      ["style", "陪伴风格", [["", "不限"], ["温柔治愈", "温柔治愈"], ["元气活力", "元气活力"], ["知性深夜", "知性深夜"]]],
    ];
    app.insertAdjacentHTML("beforeend", `<div class="sheet-backdrop" data-action="close-sheet"><div class="filter-sheet" data-sheet><div class="filter-sheet-head"><h3>筛选推荐</h3><button type="button" data-action="close-sheet">×</button></div>${groups.map(([key, title, options]) => `<section class="filter-group"><h4>${title}</h4><div class="filter-sheet-options">${options.map(([value, text]) => `<button type="button" data-filter-key="${key}" data-filter-value="${esc(value)}" class="${state.filters[key] === value ? "selected" : ""}">${text}</button>`).join("")}</div></section>`).join("")}<div class="filter-sheet-foot"><button type="button" class="filter-reset" data-action="filter-reset">重置</button><button type="button" class="primary-button filter-apply" data-action="filter-apply">查看结果</button></div></div></div>`);
  }
  function bindHomeFilter() {
    const head = app.querySelector(".section-head");
    const shuffle = head?.querySelector('[data-action="shuffle"]');
    if (!head || !shuffle || head.querySelector('[data-action="filter"]')) return;
    const actions = document.createElement("div");
    actions.className = "section-actions";
    const filter = document.createElement("button");
    filter.type = "button";
    filter.className = "filter-button";
    filter.dataset.action = "filter";
    filter.textContent = `☷ ${filterText()}`;
    shuffle.parentNode.replaceWith(actions);
    actions.append(filter, shuffle);
  }
  function home() {
    const rangeMatch = (age, range) => { const n = Number(age || 0); if (!range) return true; if (!n) return false; const [min, max] = range.split("-").map(Number); return n >= min && n <= max; };
    let list = state.chars.filter((c) => !state.category || (c.tags || []).includes(state.category));
    if (!state.category) list = list.filter((c) => rangeMatch(c.age, state.filters.age) && (!state.filters.gender || c.gender === state.filters.gender) && (!state.filters.style || c.companionStyle === state.filters.style));
    const rate = Number(state.config?.pricing?.saleCreditsPerMinute || 0);
    const roomCards = state.rooms.filter((room) => room.character);
    app.innerHTML = `${top()}<main class="live-page"><section class="section-head"><div>${state.category ? `<button class="plain-link" data-action="back-home">‹ 返回</button>` : ""}<h2>${esc(state.category || label("recommended"))}</h2><p>${list.length} ${label("online")} · 左右滑动看更多</p></div><div class="section-actions"><button class="filter-button" data-action="filter">☷ ${filterText()}</button><button class="shuffle-button" data-action="shuffle">↻ 换一批</button></div></section><section class="person-deck" id="deck">${list.length ? list.map(card).join("") : '<div class="empty-state">暂时没有符合条件的角色</div>'}</section><div class="deck-dots">${list.slice(0, 6).map((_, i) => `<i class="${i === 0 ? "active" : ""}"></i>`).join("")}</div>${roomCards.length ? `<section class="room-section"><div class="room-section-head"><h2>热门陪伴房间</h2><button class="plain-link" data-action="rooms-all">全部 ›</button></div><div class="room-strip">${roomCards.map(roomCard).join("")}</div></section>` : ""}<section class="promo-card"><span class="promo-icon">♔</span><div class="promo-copy"><strong>${label("vip")}</strong><small>${state.billing?.subscription?.status === "active" ? "订阅已生效" : "解锁 Undress 与私密资源"}</small></div><button class="promo-button" data-action="vip">查看权益</button></section><section class="billing-card"><div class="billing-title">在线视频计费</div><div class="billing-grid billing-grid-single"><div class="rate"><b>${rate > 0 ? `${rate} 积分` : "以实际配置为准"}</b><small>每分钟</small></div></div></section></main>${nav("home")}`;
    const d = document.querySelector("#deck"); d?.addEventListener("scroll", () => { const c = d.querySelector(".person-card"); if (!c) return; const index = Math.round(d.scrollLeft / (c.offsetWidth + 12)); document.querySelectorAll(".deck-dots i").forEach((x, i) => x.classList.toggle("active", i === index)); }, { passive: true });
  }
  function messages() { const rows = state.conversations.map((c) => `<div class="conversation" data-conversation-id="${esc(c.id)}"><div class="avatar">${media(c.character?.portraitUrl || c.character?.avatarUrl, "")}</div><div class="conversation-main"><div class="conversation-top"><span class="conversation-name">${esc(c.character?.name || c.title || "未命名对话")}</span><span class="conversation-time">${c.updatedAt ? esc(new Date(c.updatedAt).toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" })) : ""}</span></div><div class="conversation-preview">${esc(c.lastMessage?.content || c.preview || "进入角色直播间继续聊天")}</div></div></div>`).join(""); app.innerHTML = `<main class="live-page"><header class="page-header"><h1>${label("messages")}</h1></header><section class="conversation-list">${rows || '<div class="empty-state"><h2>还没有私信</h2><p>进入角色直播间后，相关对话会显示在这里。</p></div>'}</section></main>${nav("messages")}`; }
  function profileAvatar(u) { return photo(u) ? `<img src="${esc(photo(u))}" alt="头像">` : `<div class="profile-avatar-empty"><span>＋</span><small>上传头像</small></div>`; }
  function profile() { const u = state.user; const credits = Number(u?.credits || 0); const sub = state.billing?.subscription; app.innerHTML = `<main class="live-page profile-page"><header class="profile-header"><div class="profile-identity"><div class="profile-avatar">${u ? profileAvatar(u) : `<div class="profile-avatar-empty"><span>♙</span></div>`}</div><div><h1>${esc(u?.username || "未登录")}</h1><p>${esc(u?.occupation || "")}${u?.city ? ` · ${esc(u.city)}` : ""}</p><small>${esc(u?.bio || "登录后完善你的资料")}</small></div></div>${u ? `<button class="profile-edit-icon" data-action="edit-profile" aria-label="编辑资料">♢</button>` : ""}</header>${u ? `<section class="profile-vip-card"><div class="profile-vip-icon">♔</div><div><strong>${esc(sub?.planName || "Vipeak VIP")}</strong><small>${sub?.status === "active" ? "订阅中 · 权益已解锁" : "解锁隐私互动与私密资源"}</small></div><button data-action="vip">${sub?.status === "active" ? "管理" : "开通"}</button></section><section class="wallet-card"><div class="wallet-head"><span>我的 Vipeak 币</span><button data-action="wallet">钱包与计费</button></div><div class="wallet-balance">${credits.toLocaleString("zh-CN")}</div><small>当前账户可用余额</small><div class="wallet-actions"><button data-action="wallet">礼物记录</button><button data-action="topup">充值</button></div></section><section class="profile-menu"><button data-action="rooms"><span>♧</span><b>我的陪伴房间</b><em>›</em></button><button data-action="wallet"><span>▣</span><b>钱包与消费记录</b><em>›</em></button><button data-action="edit-profile"><span>♙</span><b>编辑资料与兴趣标签</b><em>›</em></button><button data-action="privacy"><span>⚙</span><b>隐私与安全</b><em>›</em></button></section><button class="logout-link" data-action="account">退出登录</button>` : `<div class="empty-state"><h2>登录后查看个人中心</h2><p>登录后可以管理资料、会员和钱包。</p><button class="video-button" data-action="login">登录 / 注册</button></div>`}</main>${nav("profile")}`; }
  function roleDetail(c) { const resources = Array.isArray(c.privateResources) ? c.privateResources : []; const member = state.config?.membership?.active || state.billing?.subscription?.status === "active"; app.innerHTML = `<main class="live-page role-detail-page"><section class="role-cover">${media(rolePhoto(c), c.name || "角色")}<div class="role-cover-actions"><button data-action="back-home">‹</button><span></span><button data-action="share-role">⌯</button><button data-action="favorite-role">♡</button></div><div class="role-cover-copy"><h1>${esc(c.name || "角色")}</h1><p>${esc(c.intro || "")}</p><div class="role-status"><i></i>在线 · 随时可以开始聊天 <span>AI 互动</span></div></div></section><section class="role-intro-card"><div class="role-intro-avatar">${media(rolePhoto(c), "")}</div><div class="role-intro-copy"><strong>${esc(c.greeting || "欢迎来到我的房间")}</strong><small>${esc(c.intro || "和 TA 聊聊今天的事")}</small></div><button data-action="play-greeting">▷ 试听</button></section><section class="detail-section"><div class="detail-section-title"><h2>她擅长的话题</h2></div><div class="topic-list">${(c.tags || []).map((x) => `<span class="topic-pill">${esc(x)}</span>`).join("") || '<span class="detail-empty">暂无配置话题</span>'}</div></section><section class="detail-section"><div class="detail-section-title"><h2>TA 的相册</h2><span>${member ? `${resources.length} 项` : "会员专享"}</span></div>${member && resources.length ? `<div class="resource-grid">${resources.map((r) => r.type === "video" ? `<video src="${esc(r.url)}" poster="${esc(r.thumbnailUrl || r.url)}" controls></video>` : `<img src="${esc(r.url)}" alt="${esc(r.name)}">`).join("")}</div>` : `<button class="locked-resource" data-action="vip"><span>♔</span><div><strong>订阅会员解锁私密相册</strong><small>查看角色专属图片和视频</small></div><b>›</b></button>`}</section><div class="fixed-call-bar"><button data-action="gift">♧</button><button class="primary-button" data-call-id="${esc(c.id)}">▣ ${label("call")}</button></div></main>`; }
  function interests() { return ["胶片摄影", "徒步", "看展", "咖啡", "飞盘", "脱口秀", "剧本杀", "骑行", "深夜电台", "羽毛球"]; }
  function editProfile() { const u = state.user || {}; const photos = Array.isArray(u.profilePhotos) ? u.profilePhotos : []; const selected = new Set(Array.isArray(u.interests) ? u.interests : []); app.innerHTML = `<main class="live-page edit-page"><header class="edit-header"><button data-action="back-profile">取消</button><h1>编辑资料</h1><button data-action="submit-profile" form="profileEditForm">保存</button></header><form id="profileEditForm" data-profile-form><section class="edit-section"><h3>头像与照片 <small>（最多 6 张，第一张为主图）</small></h3><div class="photo-grid">${photos.map((url, i) => `<div class="profile-photo-item"><img src="${esc(url)}" alt="照片 ${i + 1}"><button type="button" data-remove-photo="${esc(url)}">×</button>${i === 0 ? '<span>主图</span>' : ""}</div>`).join("")} ${photos.length < 6 ? '<label class="photo-upload-tile">＋<small>上传照片</small><input type="file" data-profile-photo accept="image/png,image/jpeg,image/webp" hidden></label>' : ""}</div></section><section class="edit-section"><h3>基本信息</h3><div class="edit-fields"><label>昵称<input name="username" value="${esc(u.username || "")}" required minlength="2" maxlength="40"></label><div class="edit-row"><span>性别</span><div class="gender-options"><button type="button" data-gender="male" class="${u.gender === "male" ? "selected" : ""}">男</button><button type="button" data-gender="female" class="${u.gender === "female" ? "selected" : ""}">女</button><button type="button" data-gender="other" class="${u.gender === "other" ? "selected" : ""}">其他</button></div><input type="hidden" name="gender" value="${esc(u.gender || "")}"></div><label>生日<input type="date" name="birthday" value="${esc(u.birthday || "")}"></label><label>职业<input name="occupation" value="${esc(u.occupation || "")}" maxlength="40" placeholder="填写职业"></label><label>城市<input name="city" value="${esc(u.city || "")}" maxlength="60" placeholder="填写所在城市"></label><label>简介<textarea name="bio" maxlength="120" placeholder="介绍一下自己">${esc(u.bio || "")}</textarea></label></div></section><section class="edit-section"><div class="edit-section-title"><h3>兴趣标签 <small>（已选 ${selected.size} / 8）</small></h3><button type="button" class="text-button" data-action="shuffle-interests">换一批</button></div><div class="interest-options">${interests().map((x) => `<button type="button" data-interest="${esc(x)}" class="${selected.has(x) ? "selected" : ""}">${esc(x)}</button>`).join("")}</div><input type="hidden" name="interests" value="${esc([...selected].join("|"))}"></section><section class="edit-section voice-section"><h3>语音介绍 <small>（有助于提升匹配率）</small></h3><button type="button" class="voice-upload">♧ 录制语音介绍 <small>暂未录制</small></button></section><div class="form-message" data-profile-message></div></form></main>`; }
  function vip() { const plans = state.billing?.plans || state.config?.membership?.plans || []; const active = state.billing?.subscription?.status === "active"; app.innerHTML = `<main class="live-page vip-page"><header class="detail-header"><button class="icon-button" data-action="back-profile">‹</button><h1>订阅与权益</h1><button class="text-button" data-action="wallet">消费记录</button></header><section class="vip-hero-card"><div class="vip-card-title"><span>♔</span><div><strong>Vipeak VIP</strong><small>${active ? "会员权益已生效" : "订阅会员，解锁完整体验"}</small></div></div><h2>开通即解锁隐私互动，<br>和最懂你的 TA 聊得更近一点</h2><div class="vip-badges"><span>${active ? "会员已生效" : "支持 Undress"}</span><span>私密互动已解锁</span></div></section><section class="plan-select"><div class="detail-section-title"><h3>选择套餐</h3><span>价格以后台 USD 配置为准</span></div><div class="plan-cards">${plans.map((p, i) => `<button class="plan-option ${i === 2 ? "selected" : ""}" data-plan-id="${esc(p.id)}"><strong>${esc(p.name.replace("会员", ""))}</strong><b>$${Number(p.amount).toFixed(1)}</b><small>USD</small></button>`).join("")}</div><button class="primary-button subscribe-button" data-action="subscribe-selected">${active ? "当前已订阅" : "立即开通会员"}</button></section><section class="benefit-list"><h3>会员权益</h3>${[["♧", "解锁隐私互动", "私密相册与专属陪伴模式"],["◌", "文字私信不限条", "会员期间享受专属互动"],["♧", "语音 / 视频权益", "在线聊天优先体验"],["⌁", "隐身访问", "查看 TA 的主页不留痕迹"],["◎", "专属身份标识", "房间与私信里的会员标识"]].map(([i,t,d]) => `<div><b>${i}</b><span><strong>${t}</strong><small>${d}</small></span><em>✓</em></div>`).join("")}</section></main>${nav("profile")}`; }
  function languageSheet() { app.insertAdjacentHTML("beforeend", `<div class="sheet-backdrop" data-action="close-sheet"><div class="language-sheet" data-sheet><h3>选择语言</h3>${[["zh", "简体中文"],["en", "English"],["ja", "日本語"]].map(([id,name]) => `<button data-language="${id}" class="${state.language === id ? "selected" : ""}">${name}<span>${state.language === id ? "✓" : ""}</span></button>`).join("")}</div></div>`); }
  function render() { if (state.page === "messages") messages(); else if (state.page === "profile") profile(); else if (state.page === "edit-profile") editProfile(); else if (state.page === "vip") vip(); else if (state.page === "role-detail" && state.role) roleDetail(state.role); else { home(); bindHomeFilter(); } }
  async function load() {
    const loadToken = token(); app.innerHTML = '<div class="empty-state">正在加载在线角色…</div>';
    try { state.config = await window.ChatLive.loadConfig(true); state.chars = window.ChatLive.characters(); try { state.rooms = (await api("/api/chat-live/rooms")).rooms || []; } catch { state.rooms = []; } render(); }
    catch (e) { app.innerHTML = `<div class="empty-state"><h2>暂时无法加载</h2><p>${esc(e.message)}</p></div>`; }
    if (loadToken && loadToken === token()) { try { state.user = (await api("/api/auth/me")).user; state.conversations = (await api("/api/chat/conversations")).conversations || []; } catch {} try { state.billing = (await api("/api/billing/summary")).billing || null; } catch {} if (loadToken === token()) render(); }
  }
  function openCall(id, roomId = "") { const c = state.chars.find((x) => String(x.id) === String(id)) || state.role; if (c) window.ChatLive.open(c.id, roomId ? { roomId } : {}).catch((e) => alert(e.message)); }
  async function saveProfile(form) { try { const result = await api("/api/account/profile", { method: "PATCH", body: JSON.stringify({ username: form.username.value.trim(), gender: form.gender.value, birthday: form.birthday.value, occupation: form.occupation.value, city: form.city.value, bio: form.bio.value, interests: form.interests.value ? form.interests.value.split("|").filter(Boolean) : [], profilePhotos: state.user.profilePhotos || [] }) }); state.user = result.user; state.page = "profile"; render(); } catch (error) { form.querySelector("[data-profile-message]").textContent = error.message; } }
  document.addEventListener("click", async (e) => {
    const call = e.target.closest("[data-call-id]")?.dataset.callId;
    if (call) { e.stopPropagation(); return openCall(call); }
    const room = e.target.closest("[data-room-id]");
    if (room && !e.target.closest("button")) {
      const characterId = room.dataset.roomCharacterId;
      if (!token()) { loginDialog.dataset.pending = characterId; loginDialog.dataset.pendingRoom = room.dataset.roomId || ""; loginDialog.showModal(); return; }
      return openCall(characterId, room.dataset.roomId || "");
    }
    const roleId = e.target.closest("[data-role-id]")?.dataset.roleId;
    if (roleId && !e.target.closest("button")) { state.role = state.chars.find((x) => String(x.id) === String(roleId)); if (state.role) { state.page = "role-detail"; render(); } return; }
    const filterButton = e.target.closest("[data-filter-key]");
    if (filterButton) { state.filters[filterButton.dataset.filterKey] = filterButton.dataset.filterValue || ""; filterButton.parentElement?.querySelectorAll("[data-filter-key]").forEach((button) => button.classList.toggle("selected", button === filterButton)); return; }
    const lang = e.target.closest("[data-language]")?.dataset.language;
    if (lang) { state.language = lang; localStorage.setItem("vipeakLanguage", lang); render(); return; }
    if (e.target.closest("[data-action=close-sheet]") && !e.target.closest("[data-sheet]")) { e.target.closest(".sheet-backdrop")?.remove(); return; }
    const n = e.target.closest("[data-nav]")?.dataset.nav;
    if (n) { state.page = n; render(); return; }
    const cid = e.target.closest("[data-conversation-id]")?.dataset.conversationId;
    if (cid) { location.href = `/chat.html#conversation/${encodeURIComponent(cid)}`; return; }
    const a = e.target.closest("[data-action]")?.dataset.action;
    if (a === "language-sheet") return languageSheet();
    if (a === "filter") return filterSheet();
    if (a === "filter-reset") { state.filters = { age: "", gender: "", style: "" }; e.target.closest(".sheet-backdrop")?.remove(); render(); return; }
    if (a === "filter-apply") { e.target.closest(".sheet-backdrop")?.remove(); render(); return; }
    if (a === "close-sheet") { e.target.closest(".sheet-backdrop")?.remove(); return; }
    if (a === "refresh") return load();
    if (a === "shuffle") { state.chars.push(state.chars.shift()); render(); return; }
    if (a === "back-home") { state.category = ""; state.role = null; state.page = "home"; render(); return; }
    if (a === "back-profile") { state.page = "profile"; render(); return; }
    if (a === "edit-profile") { state.page = "edit-profile"; render(); return; }
    if (a === "vip") { state.page = "vip"; render(); return; }
    if (a === "play-greeting") { const text = state.role?.greeting || ""; if (text && window.speechSynthesis) window.speechSynthesis.speak(new SpeechSynthesisUtterance(text)); return; }
    if (a === "favorite-role") { e.currentTarget.classList.toggle("selected"); return; }
    if (a === "share-role") { try { await navigator.clipboard.writeText(location.href); alert("角色链接已复制"); } catch { alert("请复制当前页面地址"); } return; }
    if (a === "subscribe-selected") { const selected = document.querySelector(".plan-option.selected")?.dataset.planId; if (!selected) return alert("请选择套餐"); if (!token()) return loginDialog.showModal(); try { const result = await api("/api/billing/subscription/orders", { method: "POST", body: JSON.stringify({ planId: selected }) }); alert(`订单已创建：${result.order?.payableAmountText || result.order?.payableAmount || "请完成支付"}`); } catch (error) { alert(error.message); } return; }
    if (a === "rooms-all") { document.querySelector(".room-strip")?.scrollTo({ left: 0, behavior: "smooth" }); return; }
    if (a === "rooms" || a === "wallet" || a === "topup" || a === "privacy" || a === "gift") { alert("该数据将在对应功能开通后显示，当前没有虚构记录。"); return; }
    if (a === "login") return loginDialog.showModal();
    if (a === "account") { if (!token()) return loginDialog.showModal(); api("/api/auth/logout", { method: "POST" }).catch(() => {}); localStorage.removeItem(TOKEN_KEY); state.user = null; state.billing = null; state.page = "profile"; render(); }
    if (a === "submit-profile") document.querySelector("#profileEditForm")?.requestSubmit();
    if (a === "shuffle-interests") { render(); }
  });
  document.addEventListener("change", async (e) => { const input = e.target.closest("[data-profile-photo]"); if (!input?.files?.[0]) return; const file = input.files[0]; input.value = ""; if (!/^image\/(png|jpeg|webp)$/.test(file.type) || file.size > 8 * 1024 * 1024) return alert("请上传 8MB 以内的 PNG、JPG 或 WEBP 图片。"); const reader = new FileReader(); reader.onload = async () => { try { const result = await api("/api/account/profile/media", { method: "POST", body: JSON.stringify({ dataUrl: reader.result }) }); state.user = result.user; editProfile(); } catch (error) { alert(error.message); } }; reader.readAsDataURL(file); });
  document.addEventListener("click", async (e) => { const gender = e.target.closest("[data-gender]"); if (gender) { const form = document.querySelector("#profileEditForm"); form?.querySelector('[name="gender"]')?.setAttribute("value", gender.dataset.gender); form?.querySelectorAll("[data-gender]").forEach((x) => x.classList.toggle("selected", x === gender)); } const interest = e.target.closest("[data-interest]"); if (interest) { interest.classList.toggle("selected"); const form = document.querySelector("#profileEditForm"); if (form) form.interests.value = [...form.querySelectorAll("[data-interest].selected")].map((x) => x.dataset.interest).join("|"); } const remove = e.target.closest("[data-remove-photo]"); if (remove) { state.user.profilePhotos = (state.user.profilePhotos || []).filter((x) => x !== remove.dataset.removePhoto); editProfile(); } });
  document.querySelector("[data-login-form]").addEventListener("submit", async (e) => { e.preventDefault(); const f = e.currentTarget; try { const r = await api("/api/auth/login-or-register", { method: "POST", body: JSON.stringify({ username: f.username.value.trim(), password: f.password.value }) }); localStorage.setItem(TOKEN_KEY, r.token); loginDialog.close(); const id = loginDialog.dataset.pending; const roomId = loginDialog.dataset.pendingRoom || ""; delete loginDialog.dataset.pending; delete loginDialog.dataset.pendingRoom; if (id) openCall(id, roomId); else { state.page = "profile"; await load(); } } catch (err) { f.querySelector("[data-login-message]").textContent = err.message; } });
  document.addEventListener("submit", (e) => { const form = e.target.closest("[data-profile-form]"); if (form) { e.preventDefault(); saveProfile(form); } });
  load();
})();
