(() => {
  const TOKEN_KEY = "raisingGameToken";
  const app = document.querySelector("#liveApp");
  const loginDialog = document.querySelector("#loginDialog");
  const state = { characters: [], config: null, user: null, page: "home", deckOffset: 0 };
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const token = () => { try { return localStorage.getItem(TOKEN_KEY) || ""; } catch { return ""; } };
  async function api(url, options = {}) { const headers = { "content-type": "application/json", ...(options.headers || {}) }; if (token()) headers.authorization = `Bearer ${token()}`; const r = await fetch(url, { ...options, headers }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.message || `请求失败（${r.status}）`); return p; }
  function imageOf(c) { return c?.portraitUrl || c?.avatarUrl || "/assets/brand/logo-mark.svg"; }
  function activeIndex() { return Math.min(5, Math.max(0, state.deckOffset)); }
  function nav(active) { return `<nav class="bottom-nav"><button class="${active === "home" ? "active" : ""}" data-nav="home"><span>⌂</span><small>首页</small></button><button class="${active === "messages" ? "active" : ""}" data-nav="messages"><span>◌</span><small>消息</small></button><button class="${active === "profile" ? "active" : ""}" data-nav="profile"><span>♙</span><small>我的</small></button></nav>`; }
  function top() { return `<header class="live-top"><div class="live-brand"><span class="brand-icon">✣</span><div><div class="brand-title">Vipeak</div><div class="brand-sub">遇见你的专属伴侣</div></div></div><button class="round-action" data-action="language" aria-label="切换语言">◎</button></header>`; }
  function characterCard(c, i) { const tags = (c.tags || []).slice(0, 3); return `<article class="person-card"><div class="person-image"><img loading="lazy" src="${esc(imageOf(c))}" alt="AI 陪伴角色${esc(c.name || "角色")}的照片"><span class="status-pill"><i></i>在线</span><span class="match-pill">默契 ${92 + ((i * 7) % 6)}%</span><div class="person-copy"><span class="person-name">${esc(c.name || "角色")}</span><span class="person-meta">${22 + (i % 7)} · ${esc(tags[0] || "AI 陪伴")}</span><div class="person-intro">${esc(c.intro || c.greeting || "温柔陪伴 · 会听你讲完一整天")}</div><div class="tag-row">${tags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div></div></div><div class="person-actions"><button class="video-button" data-character-id="${esc(c.id)}">▣ 拨打视频</button></div></article>`; }
  function roomCard(name, desc, count, image, type) { return `<article class="room-card"><div class="room-cover">${image ? `<img src="${esc(image)}" alt="${esc(name)}封面">` : ""}<span class="room-count">${count} 人在房</span><span class="room-type">${type}</span></div><div class="room-info"><div class="room-name">${esc(name)}</div><div class="room-desc">${esc(desc)}</div></div></article>`; }
  function renderHome() { const chars = state.characters; const rooms = chars.slice(0, 3); app.innerHTML = `${top()}<main class="live-page"><section class="section-head"><div><h2>为你推荐</h2><p>${chars.length || 0} 位在线 · 左右滑动看更多</p></div><div class="section-actions"><button class="filter-button" data-action="filter">⌘ 筛选</button><button class="shuffle-button" data-action="shuffle">↻ 换一批</button></div></section><section class="person-deck" id="personDeck">${chars.map(characterCard).join("")}</section><div class="deck-dots">${chars.slice(0, 6).map((_, i) => `<i class="${i === activeIndex() ? "active" : ""}"></i>`).join("")}</div><section class="room-section"><div class="section-head" style="padding:0 0 12px"><h2 style="font-size:14px">热门陪伴房间</h2><button class="plain-link" data-action="rooms">全部 ›</button></div><div class="room-strip">${roomCard("秋秋的深夜陪伴房", "1 币/分钟 · 聊到你睡着", 326, rooms[0] && imageOf(rooms[0]), "语音房")}${roomCard("小满的插画陪伴房", "2 币/分钟 · 一起画画", 128, rooms[1] && imageOf(rooms[1]), "视频房")}${roomCard("阿野的深夜电台", "1 币/分钟 · 点歌陪聊", 64, rooms[2] && imageOf(rooms[2]), "语音房")}</div></section><section class="promo-card"><span class="promo-icon">♔</span><div class="promo-copy"><strong>订阅 VIP · 解锁隐私互动</strong><small>文字私信不限条 · 语音视频 8 折</small></div><button class="promo-button" data-action="vip">查看权益</button></section><section class="billing-card"><div class="billing-title">聊天付费说明 <span>›</span></div><div class="billing-grid"><div class="rate"><b>0.5 币</b><small>文字/条</small></div><div class="rate"><b>2 币</b><small>语音/秒</small></div><div class="rate"><b>5 币</b><small>视频/秒</small></div></div></section><div class="bottom-note">已经到底啦 · 点「换一批」看看新的 TA</div></main>${nav("home")}`; bindDeck(); }
  function conversation(c, time, preview, unread = "") { return `<div class="conversation" data-character-id="${esc(c?.id || "")}"><div class="avatar"><img src="${esc(imageOf(c || {}))}" alt="${esc(c?.name || "角色")}的头像"><i></i></div><div class="conversation-main"><div class="conversation-top"><span class="conversation-name">${esc(c?.name || "角色")}</span><span class="conversation-time">${time}</span></div><div class="conversation-preview">${esc(preview)}</div></div>${unread ? `<span class="unread">${unread}</span>` : ""}</div>`; }
  function renderMessages() { const c = state.characters; app.innerHTML = `<main class="live-page"><header class="page-header"><h1>消息</h1><button class="header-button" data-action="open-room">＋ 开房间</button></header><section class="quick-actions"><button class="quick-action" data-action="rooms"><b>♧</b>私密房间</button><button class="quick-action" data-action="vip"><b style="color:#ffb45c;background:#ffb45c22">♔</b>订阅权益</button><button class="quick-action" data-action="wallet"><b style="color:#5cc8ff;background:#5cc8ff22">♢</b>礼物记录</button></section><div class="conversation-label">最近私信 · 1v1</div><section class="conversation-list">${conversation(c[0], "刚刚", "那周六的展我们几点碰？我上午都在", "3")}${conversation(c[1], "28 分钟前", "[语音] 8″ · 今天开放麦的段子讲给你听")}${conversation(c[2], "1 小时前", "这周日徒步走北高峰，你要来吗？")}${conversation(c[3], "昨天", "新本还差 1 个人，今晚陪我推凶好不好")}${conversation(c[4], "昨天", "[视频通话] 03:12 · 已结束")}</section><div class="subsection">我的房间 · 1vN</div><section class="conversation-list">${conversation(c[0], "进行中", "LIVE · 326 人在房 · 1 币/分钟")}${conversation(c[1], "昨天", "128 人在房 · 一边画一边聊")}</section><div class="bottom-note">没有更多会话了</div></main>${nav("messages")}`; }
  function renderProfile() { const c = state.characters[0] || {}; app.innerHTML = `<main class="live-page"><header class="page-header"><h1>我的</h1><button class="header-button" data-action="account">${token() ? "退出" : "登录"}</button></header><section class="profile-hero"><div class="avatar"><img src="${esc(imageOf(c))}" alt="头像"></div><div><div class="profile-name">${esc(state.user?.username || "用户")}</div><div class="profile-meta">28 · AI 陪伴体验者 · Vipeak</div></div></section><p class="profile-bio">喜欢和有趣的人聊天，也喜欢在安静的夜里听一会儿故事。</p><div class="stats"><div class="stat"><b>126</b><small>关注</small></div><div class="stat"><b>248</b><small>粉丝</small></div><div class="stat"><b>3,180</b><small>收到礼物</small></div></div><section class="vip-card"><div class="vip-row"><span class="promo-icon">♔</span><div class="vip-copy"><strong>Vipeak VIP · 订阅中</strong><small>隐私互动已解锁 · 剩余 128 天</small></div><button class="manage-button" data-action="vip">管理</button></div></section><section class="wallet-card"><div class="wallet-row"><div class="wallet-copy"><small>我的 Vipeak 币</small><div class="wallet-balance">1,280</div><small>文字 0.5 币/条 · 语音 2 币/秒 · 视频 5 币/秒</small></div></div><div class="wallet-actions"><button data-action="wallet">♢ 礼物记录</button><button data-action="topup">钱包与充值</button></div></section><section class="settings-list"><div class="settings-row"><span>♧</span><span>我的陪伴房间</span><span class="push">2 个进行中 ›</span></div><div class="settings-row"><span>♢</span><span>钱包与消费记录</span><span class="push">›</span></div><div class="settings-row"><span>♙</span><span>编辑资料与兴趣标签</span><span class="push">›</span></div><div class="settings-row"><span>⚙</span><span>隐私与安全</span><span class="push">›</span></div></section><div class="bottom-note">Vipeak · 2026</div></main>${nav("profile")}`; }
  function bindDeck() { const deck = document.querySelector("#personDeck"); if (!deck) return; deck.addEventListener("scroll", () => { const card = deck.querySelector(".person-card"); if (!card) return; state.deckOffset = Math.round(deck.scrollLeft / (card.offsetWidth + 12)); document.querySelectorAll(".deck-dots i").forEach((dot, i) => dot.classList.toggle("active", i === activeIndex())); }, { passive: true }); }
  async function load() { app.innerHTML = '<div class="empty-state">正在加载在线角色…</div>'; try { state.config = await window.ChatLive.loadConfig(true); state.characters = window.ChatLive.characters(); render(); } catch (e) { app.innerHTML = `<div class="empty-state"><h2>暂时无法加载</h2><p>${esc(e.message)}</p></div>`; } if (token()) { try { state.user = (await api("/api/auth/me")).user; } catch {} } }
  function render() { if (state.page === "messages") renderMessages(); else if (state.page === "profile") renderProfile(); else renderHome(); }
  function openCharacter(id) { const c = state.characters.find((x) => String(x.id) === String(id)); if (!token()) { loginDialog.dataset.pendingCharacter = id; loginDialog.showModal(); return; } if (c && window.ChatLive?.open) window.ChatLive.open(c.id).catch((e) => alert(e.message)); }
  document.addEventListener("click", (e) => { const navName = e.target.closest("[data-nav]")?.dataset.nav; if (navName) { state.page = navName; render(); return; } const cid = e.target.closest("[data-character-id]")?.dataset.characterId; if (cid) return openCharacter(cid); const action = e.target.closest("[data-action]")?.dataset.action; if (action === "shuffle") { state.characters = state.characters.slice(1).concat(state.characters.slice(0, 1)); state.deckOffset = 0; render(); } else if (action === "refresh") load(); else if (action === "home") { state.page = "home"; render(); } else if (action === "messages") { state.page = "messages"; render(); } else if (action === "profile" || action === "account") { if (action === "account" && token()) { localStorage.removeItem(TOKEN_KEY); state.user = null; render(); } else { state.page = "profile"; render(); } } else if (["rooms", "vip", "wallet", "topup", "open-room", "filter", "language"].includes(action)) alert(action === "filter" ? "筛选功能即将开放" : action === "rooms" ? "陪伴房间列表即将开放" : action === "vip" ? "VIP 权益页即将开放" : "功能即将开放"); });
  document.querySelector("[data-login-form]").addEventListener("submit", async (e) => { e.preventDefault(); const f = e.currentTarget; const msg = f.querySelector("[data-login-message]"); try { const r = await api("/api/auth/login-or-register", { method: "POST", body: JSON.stringify({ username: f.username.value.trim(), password: f.password.value }) }); localStorage.setItem(TOKEN_KEY, r.token); loginDialog.close(); const id = loginDialog.dataset.pendingCharacter; delete loginDialog.dataset.pendingCharacter; if (id) openCharacter(id); else { state.page = "profile"; render(); } } catch (err) { msg.textContent = err.message; } });
  load();
})();
