(() => {
  const TOKEN_KEY = "raisingGameToken";
  const app = document.querySelector("#liveApp");
  const loginDialog = document.querySelector("#loginDialog");
  const state = { chars: [], config: null, user: null, conversations: [], billing: null, page: "home", offset: 0, category: "", language: localStorage.getItem("vipeakLanguage") || "zh" };
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const token = () => { try { return localStorage.getItem(TOKEN_KEY) || ""; } catch { return ""; } };
  async function api(url, options = {}) { const h = { "content-type": "application/json", ...(options.headers || {}) }; if (token()) h.authorization = `Bearer ${token()}`; const r = await fetch(url, { cache: "no-store", ...options, headers: h }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.message || `请求失败（${r.status}）`); return p; }
  const image = (x) => x?.portraitUrl || x?.avatarUrl || x?.character?.portraitUrl || x?.character?.avatarUrl || "/assets/brand/logo-mark.svg";
  const nav = (active) => `<nav class="bottom-nav"><button class="${active === "home" ? "active" : ""}" data-nav="home"><span>⌂</span><small>首页</small></button><button class="${active === "messages" ? "active" : ""}" data-nav="messages"><span>◌</span><small>消息</small></button><button class="${active === "profile" ? "active" : ""}" data-nav="profile"><span>♙</span><small>我的</small></button></nav>`;
  const top = () => `<header class="live-top"><div class="live-brand"><span class="brand-icon">✣</span><div><div class="brand-title">Vipeak</div><div class="brand-sub">${state.language === "en" ? "Meet your companion" : "遇见你的专属伴侣"}</div></div></div><div class="top-actions"><button class="round-action" data-action="language" aria-label="语言">文</button><button class="round-action" data-action="refresh" aria-label="刷新">↻</button></div></header>`;
  function card(c) { const tags = (c.tags || []).slice(0, 3); const privateResources = Array.isArray(c.privateResources) ? c.privateResources : []; return `<article class="person-card"><div class="person-image"><img src="${esc(image(c))}" alt="${esc(c.name || "角色")}的照片"><span class="status-pill"><i></i>在线</span><div class="person-copy"><span class="person-name">${esc(c.name || "角色")}</span><div class="person-intro">${esc(c.intro || c.greeting || "和 TA 聊聊今天的事")}</div><div class="tag-row">${tags.map((x) => `<button class="tag" data-category="${esc(x)}">${esc(x)}</button>`).join("")}</div></div></div><div class="person-actions"><button class="video-button" data-character-id="${esc(c.id)}">▣ ${state.language === "en" ? "Video call" : "拨打视频"}</button></div>${privateResources.length ? `<div class="private-resource-strip">${privateResources.map((r) => r.type === "video" ? `<video src="${esc(r.url)}" poster="${esc(r.thumbnailUrl || r.url)}" controls preload="metadata"></video>` : `<img src="${esc(r.url)}" alt="${esc(r.name)}" loading="lazy" />`).join("")}</div>` : (state.config?.membership?.active ? "" : `<div class="private-locked">♔ 会员解锁私密资源</div>`)}</article>`; }
  function home() { const rate = Number(state.config?.pricing?.saleCreditsPerMinute || 0); const list = state.category ? state.chars.filter((c) => (c.tags || []).includes(state.category)) : state.chars; app.innerHTML = `${top()}<main class="live-page"><section class="section-head"><div>${state.category ? `<button class="plain-link" data-action="back-home">‹ 返回</button>` : ""}<h2>${esc(state.category || (state.language === "en" ? "Recommended" : "为你推荐"))}</h2><p>${list.length} 位在线 · 左右滑动看更多</p></div><div class="section-actions"><button class="filter-button" data-action="language">文 语言</button><button class="shuffle-button" data-action="shuffle">↻ 换一批</button></div></section><section class="person-deck" id="deck">${list.length ? list.map(card).join("") : '<div class="empty-state">暂时没有在线角色</div>'}</section><div class="deck-dots">${list.slice(0, 6).map((_, i) => `<i class="${i === state.offset ? "active" : ""}"></i>`).join("")}</div><section class="promo-card"><span class="promo-icon">♔</span><div class="promo-copy"><strong>订阅 VIP</strong><small>${state.billing?.subscription?.status === "active" ? "订阅已生效" : "解锁 Undress 与私密资源"}</small></div><button class="promo-button" data-action="vip">查看权益</button></section><section class="billing-card"><div class="billing-title">在线视频计费</div><div class="billing-grid billing-grid-single"><div class="rate"><b>${rate > 0 ? `${rate} 积分` : "以实际配置为准"}</b><small>每分钟</small></div></div></section><div class="bottom-note">角色和价格来自实时配置</div></main>${nav("home")}`; const d = document.querySelector("#deck"); d?.addEventListener("scroll", () => { const c = d.querySelector(".person-card"); if (!c) return; state.offset = Math.round(d.scrollLeft / (c.offsetWidth + 12)); document.querySelectorAll(".deck-dots i").forEach((x, i) => x.classList.toggle("active", i === state.offset)); }, { passive: true }); }
  function messages() { const rows = state.conversations.map((c) => `<div class="conversation" data-conversation-id="${esc(c.id)}"><div class="avatar"><img src="${esc(image(c))}" alt="头像"></div><div class="conversation-main"><div class="conversation-top"><span class="conversation-name">${esc(c.character?.name || c.title || "未命名对话")}</span><span class="conversation-time">${c.updatedAt ? esc(new Date(c.updatedAt).toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" })) : ""}</span></div><div class="conversation-preview">${esc(c.lastMessage || "暂无消息")}</div></div></div>`).join(""); app.innerHTML = `<main class="live-page"><header class="page-header"><h1>消息</h1><button class="header-button" data-action="rooms">＋ 开房间</button></header><section class="quick-actions"><button class="quick-action" data-action="rooms"><b>♧</b>私密房间</button><button class="quick-action" data-action="vip"><b>♔</b>订阅权益</button><button class="quick-action" data-action="wallet"><b>♢</b>消费记录</button></section><div class="conversation-label">最近私信 · 1v1</div><section class="conversation-list">${rows || '<div class="empty-state"><h2>还没有私信</h2><p>进入角色直播间后，相关对话会显示在这里。</p></div>'}</section><div class="bottom-note">${rows ? "已加载全部对话" : "暂无更多会话"}</div></main>${nav("messages")}`; }
  function profile() { const u = state.user; const credits = Number(u?.credits || 0); const sub = state.billing?.subscription; app.innerHTML = `<main class="live-page"><header class="page-header"><h1>我的</h1><div class="header-actions">${u ? `<button class="header-button" data-action="edit-profile">编辑</button><button class="header-button" data-action="account">退出</button>` : `<button class="header-button" data-action="account">登录</button>`}</div></header>${u ? `<section class="profile-hero"><div class="avatar"><img src="${esc(image(state.chars[0]))}" alt="头像"></div><div><div class="profile-name">${esc(u.username || "用户")}</div><div class="profile-meta">${esc(u.email || "未绑定邮箱")}</div></div></section><section class="wallet-card"><div class="wallet-copy"><small>我的积分</small><div class="wallet-balance">${credits.toLocaleString("zh-CN")}</div><small>当前账户可用余额</small></div><div class="wallet-actions"><button data-action="wallet">♢ 消费记录</button><button data-action="topup">充值积分</button></div></section><section class="vip-card"><div class="vip-row"><span class="promo-icon">♔</span><div class="vip-copy"><strong>${esc(sub?.planName || "订阅 VIP")}</strong><small>${esc(sub?.status === "active" ? "订阅已生效" : "解锁 Undress 与私密资源")}</small></div><button class="manage-button" data-action="vip">查看</button></div></section>` : '<div class="empty-state"><h2>登录后查看账户</h2><p>登录后可查看积分、订阅和消费记录。</p><button class="video-button" data-action="login">登录 / 注册</button></div>'}<div class="bottom-note">Vipeak · 2026</div></main>${nav("profile")}`; }
  function editProfile() { const u = state.user || {}; app.innerHTML = `<main class="live-page"><header class="page-header"><button class="header-button" data-action="back-profile">‹ 返回</button><h1>编辑资料</h1><span></span></header><form class="profile-edit-form" data-profile-form><label>昵称<input name="username" value="${esc(u.username || "")}" minlength="2" maxlength="40" required /></label><label>邮箱<input value="${esc(u.email || "未绑定")}" disabled /></label><div class="form-message" data-profile-message></div><button class="primary-button" type="submit">保存资料</button></form></main>${nav("profile")}`; }
  function vip() { const plans = state.billing?.plans || state.config?.membership?.plans || []; app.innerHTML = `<main class="live-page"><header class="page-header"><button class="header-button" data-action="back-home">‹ 返回</button><h1>会员权益</h1><span></span></header><section class="empty-state"><h2>解锁更多互动</h2><p>会员可使用 Undress，并查看角色私密图片和视频。</p>${plans.map((p) => `<button class="video-button vip-plan" data-plan-id="${esc(p.id)}">${esc(p.name)} · $${Number(p.amount).toFixed(1)} USD</button>`).join("") || '<p>暂无可购买套餐</p>'}</section></main>${nav(state.page === "profile" ? "profile" : "home")}`; }
  function render() { if (state.page === "messages") messages(); else if (state.page === "profile") profile(); else if (state.page === "edit-profile") editProfile(); else if (state.page === "vip") vip(); else home(); }
  async function load() { const loadToken = token(); app.innerHTML = '<div class="empty-state">正在加载在线角色…</div>'; try { state.config = await window.ChatLive.loadConfig(true); state.chars = window.ChatLive.characters(); render(); } catch (e) { app.innerHTML = `<div class="empty-state"><h2>暂时无法加载</h2><p>${esc(e.message)}</p></div>`; } if (loadToken && loadToken === token()) { try { state.user = (await api("/api/auth/me")).user; state.conversations = (await api("/api/chat/conversations")).conversations || []; } catch {} try { state.billing = (await api("/api/billing/summary")).billing || null; } catch {} if (loadToken === token()) render(); } }
  function openCharacter(id) { const c = state.chars.find((x) => String(x.id) === String(id)); if (!token()) { loginDialog.dataset.pending = id; loginDialog.showModal(); return; } if (c) window.ChatLive.open(c.id).catch((e) => alert(e.message)); }
  document.addEventListener("click", (e) => { const close = e.target.closest("[data-dialog-close]"); if (close) { loginDialog.close(); return; } const category = e.target.closest("[data-category]")?.dataset.category; if (category) { state.category = category; state.page = "home"; render(); return; } const n = e.target.closest("[data-nav]")?.dataset.nav; if (n) { state.page = n; render(); return; } const id = e.target.closest("[data-character-id]")?.dataset.characterId; if (id) return openCharacter(id); const cid = e.target.closest("[data-conversation-id]")?.dataset.conversationId; if (cid) return location.href = `/chat.html#conversation/${encodeURIComponent(cid)}`; const a = e.target.closest("[data-action]")?.dataset.action; if (a === "refresh") load(); else if (a === "shuffle") { state.chars.push(state.chars.shift()); state.offset = 0; render(); } else if (a === "language") { const next = state.language === "zh" ? "en" : state.language === "en" ? "ja" : "zh"; state.language = next; localStorage.setItem("vipeakLanguage", next); render(); } else if (a === "back-home") { state.category = ""; state.page = "home"; render(); } else if (a === "back-profile") { state.page = "profile"; render(); } else if (a === "edit-profile") { state.page = "edit-profile"; render(); } else if (a === "vip") { state.page = "vip"; render(); } else if (a === "account") { if (token()) { api("/api/auth/logout", { method: "POST" }).catch(() => {}); localStorage.removeItem(TOKEN_KEY); state.user = null; state.conversations = []; state.billing = null; state.page = "profile"; render(); } else loginDialog.showModal(); } else if (a === "login") loginDialog.showModal(); else if (["rooms", "wallet", "topup", "filter"].includes(a)) alert("该功能尚未开放"); });
  document.addEventListener("click", async (e) => { const plan = e.target.closest("[data-plan-id]"); if (!plan) return; if (!token()) { loginDialog.showModal(); return; } plan.disabled = true; try { const result = await api("/api/billing/subscription/orders", { method: "POST", body: JSON.stringify({ planId: plan.dataset.planId }) }); alert(`订单已创建：${result.order?.payableAmountText || result.order?.payableAmount || "请前往支付页完成付款"}`); } catch (error) { alert(error.message); } finally { plan.disabled = false; } });
  document.addEventListener("submit", async (e) => { const form = e.target.closest("[data-profile-form]"); if (!form) return; e.preventDefault(); try { const result = await api("/api/account/profile", { method: "PATCH", body: JSON.stringify({ username: form.username.value.trim() }) }); state.user = result.user; state.page = "profile"; render(); } catch (error) { form.querySelector("[data-profile-message]").textContent = error.message; } });
  document.querySelector("[data-login-form]").addEventListener("submit", async (e) => { e.preventDefault(); const f = e.currentTarget; try { const r = await api("/api/auth/login-or-register", { method: "POST", body: JSON.stringify({ username: f.username.value.trim(), password: f.password.value }) }); localStorage.setItem(TOKEN_KEY, r.token); loginDialog.close(); const id = loginDialog.dataset.pending; delete loginDialog.dataset.pending; if (id) openCharacter(id); else { state.page = "profile"; await load(); } } catch (err) { f.querySelector("[data-login-message]").textContent = err.message; } });
  load();
})();
